version: "3"
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend
  backend:
    container_name: backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"