# Generated by Django 4.0 on 2021-12-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
