# Generated by Django 4.0 on 2021-12-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanager', '0003_alter_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
